-- Historical Faith Tracker Database Schema
-- Generated by setup_schema.py

-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Create eras table
CREATE TABLE IF NOT EXISTS eras (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                name TEXT NOT NULL,
                start_year INTEGER NOT NULL,
                end_year INTEGER,
                description TEXT,
                christianity_status TEXT,
                judaism_status TEXT,
                color TEXT,
                created_at TIMESTAMPTZ DEFAULT NOW()
            );

-- Create perspectives table
CREATE TABLE IF NOT EXISTS perspectives (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                name TEXT NOT NULL,
                tradition TEXT NOT NULL,
                description TEXT,
                methodology TEXT,
                key_assumptions TEXT[],
                created_at TIMESTAMPTZ DEFAULT NOW()
            );

-- Create events table
CREATE TABLE IF NOT EXISTS events (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                title TEXT NOT NULL,
                year_start INTEGER,
                year_end INTEGER,
                date_precision TEXT DEFAULT 'year',
                era_id UUID REFERENCES eras(id),
                event_type TEXT,
                traditions_affected TEXT[],
                summary TEXT,
                detailed_narrative TEXT,
                significance TEXT,
                scholarly_consensus TEXT DEFAULT 'established',
                location TEXT,
                location_lat DECIMAL(10, 8),
                location_lng DECIMAL(11, 8),
                primary_sources TEXT[],
                embedding VECTOR(1536),
                created_at TIMESTAMPTZ DEFAULT NOW()
            );

-- Create event_interpretations table
CREATE TABLE IF NOT EXISTS event_interpretations (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                event_id UUID REFERENCES events(id) ON DELETE CASCADE,
                perspective_id UUID REFERENCES perspectives(id),
                interpretation TEXT NOT NULL,
                key_points TEXT[],
                areas_of_agreement TEXT[],
                areas_of_disagreement TEXT[],
                sources TEXT[],
                created_at TIMESTAMPTZ DEFAULT NOW(),
                UNIQUE(event_id, perspective_id)
            );

-- Create figures table
CREATE TABLE IF NOT EXISTS figures (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                name TEXT NOT NULL,
                alternate_names TEXT[],
                birth_year INTEGER,
                death_year INTEGER,
                tradition TEXT,
                roles TEXT[],
                biography TEXT,
                key_contributions TEXT[],
                controversies TEXT[],
                embedding VECTOR(1536),
                created_at TIMESTAMPTZ DEFAULT NOW()
            );

-- Create movements table
CREATE TABLE IF NOT EXISTS movements (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                name TEXT NOT NULL,
                tradition TEXT,
                start_year INTEGER,
                end_year INTEGER,
                description TEXT,
                core_beliefs TEXT[],
                key_figures TEXT[],
                parent_movement_id UUID REFERENCES movements(id),
                created_at TIMESTAMPTZ DEFAULT NOW()
            );

-- Create scripture_usage table
CREATE TABLE IF NOT EXISTS scripture_usage (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                passage_reference TEXT NOT NULL,
                passage_text TEXT,
                event_id UUID REFERENCES events(id),
                figure_id UUID REFERENCES figures(id),
                movement_id UUID REFERENCES movements(id),
                usage_year INTEGER,
                usage_era_id UUID REFERENCES eras(id),
                usage_type TEXT,
                usage_context TEXT,
                how_used TEXT,
                interpretation_given TEXT,
                faithful_to_original_context TEXT,
                impact_description TEXT,
                perspective_views JSONB,
                embedding VECTOR(1536),
                created_at TIMESTAMPTZ DEFAULT NOW()
            );

-- Create primary_sources table
CREATE TABLE IF NOT EXISTS primary_sources (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                title TEXT NOT NULL,
                author TEXT,
                author_figure_id UUID REFERENCES figures(id),
                date_written INTEGER,
                source_type TEXT,
                tradition TEXT,
                url TEXT,
                archive_source TEXT,
                content_summary TEXT,
                created_at TIMESTAMPTZ DEFAULT NOW()
            );

-- Create index on events.era_id
CREATE INDEX IF NOT EXISTS idx_events_era ON events(era_id);

-- Create index on events.year_start
CREATE INDEX IF NOT EXISTS idx_events_year ON events(year_start);

-- Create index on events.event_type
CREATE INDEX IF NOT EXISTS idx_events_type ON events(event_type);

-- Create GIN index on events.traditions_affected
CREATE INDEX IF NOT EXISTS idx_events_traditions ON events USING GIN(traditions_affected);

-- Create index on scripture_usage.passage_reference
CREATE INDEX IF NOT EXISTS idx_scripture_passage ON scripture_usage(passage_reference);

-- Create index on scripture_usage.usage_year
CREATE INDEX IF NOT EXISTS idx_scripture_year ON scripture_usage(usage_year);

-- Create index on scripture_usage.usage_type
CREATE INDEX IF NOT EXISTS idx_scripture_type ON scripture_usage(usage_type);

-- Create index on figures.tradition
CREATE INDEX IF NOT EXISTS idx_figures_tradition ON figures(tradition);

-- Create index on figures.birth_year and death_year
CREATE INDEX IF NOT EXISTS idx_figures_years ON figures(birth_year, death_year);

-- Create search_events function
CREATE OR REPLACE FUNCTION search_events(
                query_embedding VECTOR(1536),
                match_threshold FLOAT DEFAULT 0.5,
                match_count INT DEFAULT 10
            )
            RETURNS TABLE (
                id UUID,
                title TEXT,
                summary TEXT,
                year_start INTEGER,
                similarity FLOAT
            )
            LANGUAGE plpgsql
            AS $$
            BEGIN
                RETURN QUERY
                SELECT
                    e.id,
                    e.title,
                    e.summary,
                    e.year_start,
                    1 - (e.embedding <=> query_embedding) AS similarity
                FROM events e
                WHERE e.embedding IS NOT NULL
                AND 1 - (e.embedding <=> query_embedding) > match_threshold
                ORDER BY e.embedding <=> query_embedding
                LIMIT match_count;
            END;
            $$;

-- Create search_scripture_usage function
CREATE OR REPLACE FUNCTION search_scripture_usage(
                query_embedding VECTOR(1536),
                match_threshold FLOAT DEFAULT 0.5,
                match_count INT DEFAULT 10
            )
            RETURNS TABLE (
                id UUID,
                passage_reference TEXT,
                how_used TEXT,
                usage_year INTEGER,
                similarity FLOAT
            )
            LANGUAGE plpgsql
            AS $$
            BEGIN
                RETURN QUERY
                SELECT
                    s.id,
                    s.passage_reference,
                    s.how_used,
                    s.usage_year,
                    1 - (s.embedding <=> query_embedding) AS similarity
                FROM scripture_usage s
                WHERE s.embedding IS NOT NULL
                AND 1 - (s.embedding <=> query_embedding) > match_threshold
                ORDER BY s.embedding <=> query_embedding
                LIMIT match_count;
            END;
            $$;

-- Create search_figures function
CREATE OR REPLACE FUNCTION search_figures(
                query_embedding VECTOR(1536),
                match_threshold FLOAT DEFAULT 0.5,
                match_count INT DEFAULT 10
            )
            RETURNS TABLE (
                id UUID,
                name TEXT,
                biography TEXT,
                tradition TEXT,
                similarity FLOAT
            )
            LANGUAGE plpgsql
            AS $$
            BEGIN
                RETURN QUERY
                SELECT
                    f.id,
                    f.name,
                    f.biography,
                    f.tradition,
                    1 - (f.embedding <=> query_embedding) AS similarity
                FROM figures f
                WHERE f.embedding IS NOT NULL
                AND 1 - (f.embedding <=> query_embedding) > match_threshold
                ORDER BY f.embedding <=> query_embedding
                LIMIT match_count;
            END;
            $$;

-- Create get_event_perspectives function
CREATE OR REPLACE FUNCTION get_event_perspectives(event_uuid UUID)
            RETURNS TABLE (
                perspective_name TEXT,
                tradition TEXT,
                interpretation TEXT,
                key_points TEXT[],
                sources TEXT[]
            )
            LANGUAGE plpgsql
            AS $$
            BEGIN
                RETURN QUERY
                SELECT
                    p.name,
                    p.tradition,
                    ei.interpretation,
                    ei.key_points,
                    ei.sources
                FROM event_interpretations ei
                JOIN perspectives p ON ei.perspective_id = p.id
                WHERE ei.event_id = event_uuid
                ORDER BY p.name;
            END;
            $$;

-- Create get_passage_history function
CREATE OR REPLACE FUNCTION get_passage_history(passage TEXT)
            RETURNS TABLE (
                usage_year INTEGER,
                usage_type TEXT,
                how_used TEXT,
                faithful_to_original TEXT,
                event_title TEXT,
                figure_name TEXT
            )
            LANGUAGE plpgsql
            AS $$
            BEGIN
                RETURN QUERY
                SELECT
                    su.usage_year,
                    su.usage_type,
                    su.how_used,
                    su.faithful_to_original_context,
                    e.title,
                    f.name
                FROM scripture_usage su
                LEFT JOIN events e ON su.event_id = e.id
                LEFT JOIN figures f ON su.figure_id = f.id
                WHERE su.passage_reference ILIKE '%' || passage || '%'
                ORDER BY su.usage_year;
            END;
            $$;

-- Create get_timeline_events function
CREATE OR REPLACE FUNCTION get_timeline_events(
                start_year INTEGER,
                end_year INTEGER,
                tradition_filter TEXT[] DEFAULT NULL,
                event_type_filter TEXT[] DEFAULT NULL
            )
            RETURNS TABLE (
                id UUID,
                title TEXT,
                year_start INTEGER,
                year_end INTEGER,
                event_type TEXT,
                traditions_affected TEXT[],
                summary TEXT,
                location TEXT,
                location_lat DECIMAL,
                location_lng DECIMAL
            )
            LANGUAGE plpgsql
            AS $$
            BEGIN
                RETURN QUERY
                SELECT
                    e.id,
                    e.title,
                    e.year_start,
                    e.year_end,
                    e.event_type,
                    e.traditions_affected,
                    e.summary,
                    e.location,
                    e.location_lat,
                    e.location_lng
                FROM events e
                WHERE e.year_start >= start_year
                AND e.year_start <= end_year
                AND (tradition_filter IS NULL OR e.traditions_affected && tradition_filter)
                AND (event_type_filter IS NULL OR e.event_type = ANY(event_type_filter))
                ORDER BY e.year_start;
            END;
            $$;

-- Seed Data
-- Insert seed data for eras
INSERT INTO eras (name, start_year, end_year, description, color) VALUES
            ('Apostolic Era', -4, 100, 'From Jesus birth to the death of the last apostle', '#4CAF50'),
            ('Ante-Nicene Period', 100, 325, 'Early church before the Council of Nicaea', '#8BC34A'),
            ('Post-Nicene/Byzantine', 325, 600, 'Age of ecumenical councils and creeds', '#CDDC39'),
            ('Early Medieval', 600, 1000, 'Rise of Islam, monasticism, Charlemagne', '#FFEB3B'),
            ('High Medieval', 1000, 1300, 'Crusades, Scholasticism, cathedrals', '#FFC107'),
            ('Late Medieval', 1300, 1517, 'Pre-Reformation, Black Death, mysticism', '#FF9800'),
            ('Reformation', 1517, 1648, 'Protestant Reformation and Catholic Counter-Reformation', '#FF5722'),
            ('Post-Reformation', 1648, 1800, 'Enlightenment, pietism, revivals', '#795548'),
            ('Modern Era', 1800, 1950, 'Liberalism, fundamentalism, world wars', '#607D8B'),
            ('Contemporary', 1950, 2024, 'Vatican II, ecumenism, globalization', '#9C27B0')
            ON CONFLICT DO NOTHING;

-- Insert seed data for perspectives
INSERT INTO perspectives (name, tradition, description, methodology) VALUES
            ('Eastern Orthodox', 'Christianity', 'The perspective of the Eastern Orthodox churches', 'Emphasis on Holy Tradition, patristic consensus, and liturgical continuity'),
            ('Roman Catholic', 'Christianity', 'The perspective of the Roman Catholic Church', 'Magisterial interpretation, papal authority, and development of doctrine'),
            ('Protestant', 'Christianity', 'The perspective of Protestant traditions', 'Sola scriptura, historical-critical methods, and confessional standards'),
            ('Orthodox Judaism', 'Judaism', 'The perspective of traditional/Orthodox Judaism', 'Halakhic interpretation, Talmudic methodology, and rabbinic authority'),
            ('Academic/Secular', 'Secular', 'The perspective of secular historical scholarship', 'Historical-critical method, empirical evidence, and neutrality toward theological claims')
            ON CONFLICT DO NOTHING;
